name: Build Docker Image and Upload Artifact

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        # Замените kreonike1 на ваш логин, чтобы тег был корректным
        run: docker build -t kreonike1/converter-project:latest .

      - name: Save Docker image to tar file
        run: docker save --output image.tar kreonike1/converter-project:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: converter-image
          path: image.tar
